### ISSUE TITLE
git-srep: improve output, add --dry-run option

### ISSUE THREAD

**Issue by gahooa** [appcove/git-excess#4]
Now that the git-srep command is working well, it's time to evaluate some of the _polish_ that can be applied to make it nicer.

- [ ] Output and messages should be nicely formatted
- [ ] In the case of unstaged content, the command should print out a nice message, showing exactly which files (nicely formatted similar to git status) were in conflict.
- [ ] `--dry-run` option should be added which will "say" what sed command would be called, but not actually call it
- [ ] When command is run successfully, it should print the list of files out that were passed through sed, again, similar to the format of git status.

Thanks!

**Comment by DilecPadovani** [comment]
So `--dry-run`should make git-srep print, for example" : `seg "s/search/replace/g" files.txt`.  Is this correct?
